### ISSUE TITLE
Mangrove Propagates always simulate growth 1.20.4 

### ISSUE THREAD

**Issue by mahss-io** [InZan17/Unloaded-Activity#24]
This might have been fixed already but when playing in 1.20.4 on a server, started in a Mangrove biome and I believe it would try to simulate the propagule hanging from the the Mangrove trees. From there it would successfully grow the tree, creating more propagule causing the biome to over grow after coming back to the loaded chunks after a few times.
I was able to make a patched version which I believe either ignored propagule or did a block below check as well.

**Comment by rgmcwill** [comment]
I will post more tomorrow when I can recreate/look at my changes for the patch. Only brining it up now as I am updating my server 1.21.
