### ISSUE TITLE
Blazing Bamboo compatibility

### ISSUE THREAD

**Issue by jshipley** [InZan17/Unloaded-Activity#27]
When this mod is being used with the Blazing Bamboo mod, it replaces the Blazing Bamboo block state with the vanilla Bamboo block state.

Blazing Bamboo extends the BambooShootBlock and BambooSapling block. When the bamboo blocks get updated in BambooMixin and BambooSaplingMixin, the blockstate gets set to the Blocks.BAMBOO default blockstate instead of to the subclass default blockstate.

**Comment by PaddedShaman** [comment]
Just to +1 this, it also happens to the custom bamboo types in Ferdinand's Flowers (Forge 1.19.2) for the same reason.

**Comment by InZan17** [comment]
I changed the simulation function for the bamboo blocks so it now works with modded bamboo blocks.

I will update the mod in a bit. Thanks for reporting this issue!
